"""
SQLAlchemy models for trading bot persistence.

Defines Trade and Signal models for storing historical data.
"""
from datetime import datetime
from typing import Optional
import uuid

from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, Enum as SQLEnum
from sqlalchemy.dialects.sqlite import CHAR
import enum

from app.core.database import Base


class OrderSide(str, enum.Enum):
    """Order side enumeration."""
    BUY = "buy"
    SELL = "sell"


class Trade(Base):
    """
    Model for storing executed trades.
    
    Tracks all buy/sell orders executed by the bot, including
    price, quantity, and realized PnL.
    """
    __tablename__ = "trades"
    
    # Primary key as UUID string
    id = Column(CHAR(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Timestamp when trade was executed
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    
    # Trading pair (e.g., 'BTC/USDT')
    symbol = Column(String(20), nullable=False, index=True)
    
    # Order side: 'buy' or 'sell'
    side = Column(SQLEnum(OrderSide), nullable=False)
    
    # Execution price
    price = Column(Float, nullable=False)
    
    # Quantity traded (in base currency)
    quantity = Column(Float, nullable=False)
    
    # Realized profit/loss for this trade (nullable if not yet calculated)
    pnl = Column(Float, nullable=True)
    
    def __repr__(self) -> str:
        return (
            f"<Trade(id={self.id[:8]}..., symbol={self.symbol}, "
            f"side={self.side.value}, price={self.price}, qty={self.quantity})>"
        )


class Signal(Base):
    """
    Model for storing strategy signals.
    
    Records all trading signals generated by strategies, along with
    metadata about indicator values that triggered the signal.
    """
    __tablename__ = "signals"
    
    # Auto-incrementing integer primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Timestamp when signal was generated
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    
    # Trading pair (e.g., 'BTC/USDT')
    symbol = Column(String(20), nullable=False, index=True)
    
    # Signal value: 1 (buy), -1 (sell), 0 (neutral/hold)
    signal_value = Column(Integer, nullable=False)
    
    # Signal metadata: JSON column storing indicator values and signal context
    # Example: {"fast_sma": 50000, "slow_sma": 48000, "price": 51000}
    # Note: Using 'signal_metadata' instead of 'metadata' (reserved in SQLAlchemy)
    signal_metadata = Column(JSON, nullable=True)
    
    def __repr__(self) -> str:
        signal_type = "BUY" if self.signal_value == 1 else "SELL" if self.signal_value == -1 else "NEUTRAL"
        return (
            f"<Signal(id={self.id}, symbol={self.symbol}, "
            f"type={signal_type}, timestamp={self.timestamp})>"
        )

